"""updated Bill

Revision ID: 0058ac4e91d3
Revises: 16e56393e373
Create Date: 2022-09-15 17:23:15.276628

"""
from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0058ac4e91d3'
down_revision = '16e56393e373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('amount', sa.Numeric(), nullable=False))
    op.add_column('bill', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('bill', sa.Column('order_created_date', sa.DateTime(), nullable=True))
    op.add_column('bill', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('bill', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bill', 'product_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.create_foreign_key(None, 'bill', 'order', ['order_id'], ['id'])
    op.drop_column('bill', 'created_order_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('created_order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bill', type_='foreignkey')
    op.alter_column('bill', 'product_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('bill', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bill', 'status')
    op.drop_column('bill', 'order_id')
    op.drop_column('bill', 'order_created_date')
    op.drop_column('bill', 'comment')
    op.drop_column('bill', 'amount')
    # ### end Alembic commands ###
